export const countries = [
  { name: "Select Country", code: "01", flag: "noflag" },
  { name: "Afghanistan", code: "AF", flag: "/flags/af.svg" },
  { name: "Åland Islands", code: "AX", flag: "/flags/ax.svg" },
  { name: "Albania", code: "AL", flag: "/flags/al.svg" },
  { name: "Algeria", code: "DZ", flag: "/flags/dz.svg" },
  { name: "American Samoa", code: "AS", flag: "/flags/as.svg" },
  { name: "AndorrA", code: "AD", flag: "/flags/ad.svg" },
  { name: "Angola", code: "AO", flag: "/flags/ao.svg" },
  { name: "Anguilla", code: "AI", flag: "/flags/ai.svg" },
  { name: "Antarctica", code: "AQ", flag: "/flags/aq.svg" },
  { name: "Antigua and Barbuda", code: "AG", flag: "/flags/ag.svg" },
  { name: "Argentina", code: "AR", flag: "/flags/ar.svg" },
  { name: "Armenia", code: "AM", flag: "/flags/am.svg" },
  { name: "Aruba", code: "AW", flag: "/flags/aw.svg" },
  { name: "Australia", code: "AU", flag: "/flags/au.svg" },
  { name: "Austria", code: "AT", flag: "/flags/at.svg" },
  { name: "Azerbaijan", code: "AZ", flag: "/flags/az.svg" },
  { name: "Bahamas", code: "BS", flag: "/flags/bs.svg" },
  { name: "Bahrain", code: "BH", flag: "/flags/bh.svg" },
  { name: "Bangladesh", code: "BD", flag: "/flags/bd.svg" },
  { name: "Barbados", code: "BB", flag: "/flags/bb.svg" },
  { name: "Belarus", code: "BY", flag: "/flags/by.svg" },
  { name: "Belgium", code: "BE", flag: "/flags/be.svg" },
  { name: "Belize", code: "BZ", flag: "/flags/bz.svg" },
  { name: "Benin", code: "BJ", flag: "/flags/bj.svg" },
  { name: "Bermuda", code: "BM", flag: "/flags/bm.svg" },
  { name: "Bhutan", code: "BT", flag: "/flags/bt.svg" },
  { name: "Bolivia", code: "BO", flag: "/flags/bo.svg" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "/flags/ba.svg" },
  { name: "Botswana", code: "BW", flag: "/flags/bw.svg" },
  { name: "Bouvet Island", code: "BV", flag: "/flags/bv.svg" },
  { name: "Brazil", code: "BR", flag: "/flags/br.svg" },
  { name: "British Indian Ocean Territory", code: "IO", flag: "/flags/io.svg" },
  { name: "Brunei Darussalam", code: "BN", flag: "/flags/bn.svg" },
  { name: "Bulgaria", code: "BG", flag: "/flags/bg.svg" },
  { name: "Burkina Faso", code: "BF", flag: "/flags/bf.svg" },
  { name: "Burundi", code: "BI", flag: "/flags/bi.svg" },
  { name: "Cambodia", code: "KH", flag: "/flags/kh.svg" },
  { name: "Cameroon", code: "CM", flag: "/flags/cm.svg" },
  { name: "Canada", code: "CA", flag: "/flags/ca.svg" },
  { name: "Cape Verde", code: "CV", flag: "/flags/cv.svg" },
  { name: "Cayman Islands", code: "KY", flag: "/flags/ky.svg" },
  { name: "Central African Republic", code: "CF", flag: "/flags/cf.svg" },
  { name: "Chad", code: "TD", flag: "/flags/td.svg" },
  { name: "Chile", code: "CL", flag: "/flags/cl.svg" },
  { name: "China", code: "CN", flag: "/flags/cn.svg" },
  { name: "Christmas Island", code: "CX", flag: "/flags/cx.svg" },
  { name: "Cocos (Keeling) Islands", code: "CC", flag: "/flags/cc.svg" },
  { name: "Colombia", code: "CO", flag: "/flags/co.svg" },
  { name: "Comoros", code: "KM", flag: "/flags/km.svg" },
  { name: "Congo", code: "CG", flag: "/flags/cg.svg" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    flag: "/flags/cd.svg",
  },
  { name: "Cook Islands", code: "CK", flag: "/flags/ck.svg" },
  { name: "Costa Rica", code: "CR", flag: "/flags/cr.svg" },
  { name: "Cote D'Ivoire", code: "CI", flag: "/flags/ci.svg" },
  { name: "Croatia", code: "HR", flag: "/flags/hr.svg" },
  { name: "Cuba", code: "CU", flag: "/flags/cu.svg" },
  { name: "Cyprus", code: "CY", flag: "/flags/cy.svg" },
  { name: "Czech Republic", code: "CZ", flag: "/flags/cz.svg" },
  { name: "Denmark", code: "DK", flag: "/flags/dk.svg" },
  { name: "Djibouti", code: "DJ", flag: "/flags/dj.svg" },
  { name: "Dominica", code: "DM", flag: "/flags/dm.svg" },
  { name: "Dominican Republic", code: "DO", flag: "/flags/do.svg" },
  { name: "Ecuador", code: "EC", flag: "/flags/ec.svg" },
  { name: "Egypt", code: "EG", flag: "/flags/eg.svg" },
  { name: "El Salvador", code: "SV", flag: "/flags/sv.svg" },
  { name: "Equatorial Guinea", code: "GQ", flag: "/flags/gq.svg" },
  { name: "Eritrea", code: "ER", flag: "/flags/er.svg" },
  { name: "Estonia", code: "EE", flag: "/flags/ee.svg" },
  { name: "Ethiopia", code: "ET", flag: "/flags/et.svg" },
  { name: "Falkland Islands (Malvinas)", code: "FK", flag: "/flags/fk.svg" },
  { name: "Faroe Islands", code: "FO", flag: "/flags/fo.svg" },
  { name: "Fiji", code: "FJ", flag: "/flags/fj.svg" },
  { name: "Finland", code: "FI", flag: "/flags/fi.svg" },
  { name: "France", code: "FR", flag: "/flags/fr.svg" },
  { name: "French Guiana", code: "GF", flag: "/flags/gf.svg" },
  { name: "French Polynesia", code: "PF", flag: "/flags/pf.svg" },
  { name: "French Southern Territories", code: "TF", flag: "/flags/tf.svg" },
  { name: "Gabon", code: "GA", flag: "/flags/ga.svg" },
  { name: "Gambia", code: "GM", flag: "/flags/gm.svg" },
  { name: "Georgia", code: "GE", flag: "/flags/ge.svg" },
  { name: "Germany", code: "DE", flag: "/flags/de.svg" },
  { name: "Ghana", code: "GH", flag: "/flags/gh.svg" },
  { name: "Gibraltar", code: "GI", flag: "/flags/gi.svg" },
  { name: "Greece", code: "GR", flag: "/flags/gr.svg" },
  { name: "Greenland", code: "GL", flag: "/flags/gl.svg" },
  { name: "Grenada", code: "GD", flag: "/flags/gd.svg" },
  { name: "Guadeloupe", code: "GP", flag: "/flags/gp.svg" },
  { name: "Guam", code: "GU", flag: "/flags/gu.svg" },
  { name: "Guatemala", code: "GT", flag: "/flags/gt.svg" },
  { name: "Guernsey", code: "GG", flag: "/flags/gg.svg" },
  { name: "Guinea", code: "GN", flag: "/flags/gn.svg" },
  { name: "Guinea-Bissau", code: "GW", flag: "/flags/gw.svg" },
  { name: "Guyana", code: "GY", flag: "/flags/gy.svg" },
  { name: "Haiti", code: "HT", flag: "/flags/ht.svg" },
  {
    name: "Heard Island and Mcdonald Islands",
    code: "HM",
    flag: "/flags/hm.svg",
  },
  { name: "Holy See (Vatican City State)", code: "VA", flag: "/flags/va.svg" },
  { name: "Honduras", code: "HN", flag: "/flags/hn.svg" },
  { name: "Hong Kong", code: "HK", flag: "/flags/hk.svg" },
  { name: "Hungary", code: "HU", flag: "/flags/hu.svg" },
  { name: "Iceland", code: "IS", flag: "/flags/is.svg" },
  { name: "India", code: "IN", flag: "/flags/in.svg" },
  { name: "Indonesia", code: "ID", flag: "/flags/id.svg" },
  { name: "Iran, Islamic Republic Of", code: "IR", flag: "/flags/ir.svg" },
  { name: "Iraq", code: "IQ", flag: "/flags/iq.svg" },
  { name: "Ireland", code: "IE", flag: "/flags/ie.svg" },
  { name: "Isle of Man", code: "IM", flag: "/flags/im.svg" },
  { name: "Israel", code: "IL", flag: "/flags/il.svg" },
  { name: "Italy", code: "IT", flag: "/flags/it.svg" },
  { name: "Jamaica", code: "JM", flag: "/flags/jm.svg" },
  { name: "Japan", code: "JP", flag: "/flags/jp.svg" },
  { name: "Jersey", code: "JE", flag: "/flags/je.svg" },
  { name: "Jordan", code: "JO", flag: "/flags/jo.svg" },
  { name: "Kazakhstan", code: "KZ", flag: "/flags/kz.svg" },
  { name: "Kenya", code: "KE", flag: "/flags/ke.svg" },
  { name: "Kiribati", code: "KI", flag: "/flags/ki.svg" },
  {
    name: "Korea, Democratic People'S Republic of",
    code: "KP",
    flag: "/flags/kp.svg",
  },
  { name: "Korea, Republic of", code: "KR", flag: "/flags/kr.svg" },
  { name: "Kuwait", code: "KW", flag: "/flags/kw.svg" },
  { name: "Kosovo", code: "XK", flag: "/flags/xk.svg" },
  { name: "Kyrgyzstan", code: "KG", flag: "/flags/kg.svg" },
  {
    name: "Lao People'S Democratic Republic",
    code: "LA",
    flag: "/flags/la.svg",
  },
  { name: "Latvia", code: "LV", flag: "/flags/lv.svg" },
  { name: "Lebanon", code: "LB", flag: "/flags/lb.svg" },
  { name: "Lesotho", code: "LS", flag: "/flags/ls.svg" },
  { name: "Liberia", code: "LR", flag: "/flags/lr.svg" },
  { name: "Libyan Arab Jamahiriya", code: "LY", flag: "/flags/ly.svg" },
  { name: "Liechtenstein", code: "LI", flag: "/flags/li.svg" },
  { name: "Lithuania", code: "LT", flag: "/flags/lt.svg" },
  { name: "Luxembourg", code: "LU", flag: "/flags/lu.svg" },
  { name: "Macao", code: "MO", flag: "/flags/mo.svg" },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    flag: "/flags/mk.svg",
  },
  { name: "Madagascar", code: "MG", flag: "/flags/mg.svg" },
  { name: "Malawi", code: "MW", flag: "/flags/mw.svg" },
  { name: "Malaysia", code: "MY", flag: "/flags/my.svg" },
  { name: "Maldives", code: "MV", flag: "/flags/mv.svg" },
  { name: "Mali", code: "ML", flag: "/flags/ml.svg" },
  { name: "Malta", code: "MT", flag: "/flags/mt.svg" },
  { name: "Marshall Islands", code: "MH", flag: "/flags/mh.svg" },
  { name: "Martinique", code: "MQ", flag: "/flags/mq.svg" },
  { name: "Mauritania", code: "MR", flag: "/flags/mr.svg" },
  { name: "Mauritius", code: "MU", flag: "/flags/mu.svg" },
  { name: "Mayotte", code: "YT", flag: "/flags/yt.svg" },
  { name: "Mexico", code: "MX", flag: "/flags/mx.svg" },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    flag: "/flags/fm.svg",
  },
  { name: "Moldova, Republic of", code: "MD", flag: "/flags/md.svg" },
  { name: "Monaco", code: "MC", flag: "/flags/mc.svg" },
  { name: "Mongolia", code: "MN", flag: "/flags/mn.svg" },
  { name: "Montserrat", code: "MS", flag: "/flags/ms.svg" },
  { name: "Morocco", code: "MA", flag: "/flags/ma.svg" },
  { name: "Mozambique", code: "MZ", flag: "/flags/mz.svg" },
  { name: "Myanmar", code: "MM", flag: "/flags/mm.svg" },
  { name: "Namibia", code: "NA", flag: "/flags/na.svg" },
  { name: "Nauru", code: "NR", flag: "/flags/nr.svg" },
  { name: "Nepal", code: "NP", flag: "/flags/np.svg" },
  { name: "Netherlands", code: "NL", flag: "/flags/nl.svg" },
  { name: "Netherlands Antilles", code: "AN", flag: "/flags/an.svg" },
  { name: "New Caledonia", code: "NC", flag: "/flags/nc.svg" },
  { name: "New Zealand", code: "NZ", flag: "/flags/nz.svg" },
  { name: "Nicaragua", code: "NI", flag: "/flags/ni.svg" },
  { name: "Niger", code: "NE", flag: "/flags/ne.svg" },
  { name: "Nigeria", code: "NG", flag: "/flags/ng.svg" },
  { name: "Niue", code: "NU", flag: "/flags/nu.svg" },
  { name: "Norfolk Island", code: "NF", flag: "/flags/nf.svg" },
  { name: "Northern Mariana Islands", code: "MP", flag: "/flags/mp.svg" },
  { name: "Norway", code: "NO", flag: "/flags/no.svg" },
  { name: "Oman", code: "OM", flag: "/flags/om.svg" },
  { name: "Pakistan", code: "PK", flag: "/flags/pk.svg" },
  { name: "Palau", code: "PW", flag: "/flags/pw.svg" },
  {
    name: "Palestinian Territory, Occupied",
    code: "PS",
    flag: "/flags/ps.svg",
  },
  { name: "Panama", code: "PA", flag: "/flags/pa.svg" },
  { name: "Papua New Guinea", code: "PG", flag: "/flags/pg.svg" },
  { name: "Paraguay", code: "PY", flag: "/flags/py.svg" },
  { name: "Peru", code: "PE", flag: "/flags/pe.svg" },
  { name: "Philippines", code: "PH", flag: "/flags/ph.svg" },
  { name: "Pitcairn", code: "PN", flag: "/flags/pn.svg" },
  { name: "Poland", code: "PL", flag: "/flags/pl.svg" },
  { name: "Portugal", code: "PT", flag: "/flags/pt.svg" },
  { name: "Puerto Rico", code: "PR", flag: "/flags/pr.svg" },
  { name: "Qatar", code: "QA", flag: "/flags/qa.svg" },
  { name: "Reunion", code: "RE", flag: "/flags/re.svg" },
  { name: "Romania", code: "RO", flag: "/flags/ro.svg" },
  { name: "Russian Federation", code: "RU", flag: "/flags/ru.svg" },
  { name: "RWANDA", code: "RW", flag: "/flags/rw.svg" },
  { name: "Saint Helena", code: "SH", flag: "/flags/sh.svg" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "/flags/kn.svg" },
  { name: "Saint Lucia", code: "LC", flag: "/flags/lc.svg" },
  { name: "Saint Pierre and Miquelon", code: "PM", flag: "/flags/pm.svg" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "/flags/vc.svg",
  },
  { name: "Samoa", code: "WS", flag: "/flags/ws.svg" },
  { name: "San Marino", code: "SM", flag: "/flags/sm.svg" },
  { name: "Sao Tome and Principe", code: "ST", flag: "/flags/st.svg" },
  { name: "Saudi Arabia", code: "SA", flag: "/flags/sa.svg" },
  { name: "Senegal", code: "SN", flag: "/flags/sn.svg" },
  { name: "Montenegro", code: "ME", flag: "/flags/me.svg" },
  { name: "Seychelles", code: "SC", flag: "/flags/sc.svg" },
  { name: "Sierra Leone", code: "SL", flag: "/flags/sl.svg" },
  { name: "Singapore", code: "SG", flag: "/flags/sg.svg" },
  { name: "Slovakia", code: "SK", flag: "/flags/sk.svg" },
  { name: "Slovenia", code: "SI", flag: "/flags/si.svg" },
  { name: "Solomon Islands", code: "SB", flag: "/flags/sb.svg" },
  { name: "Somalia", code: "SO", flag: "/flags/so.svg" },
  { name: "South Africa", code: "ZA", flag: "/flags/za.svg" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    flag: "/flags/gs.svg",
  },
  { name: "Spain", code: "ES", flag: "/flags/es.svg" },
  { name: "Sri Lanka", code: "LK", flag: "/flags/lk.svg" },
  { name: "Sudan", code: "SD", flag: "/flags/sd.svg" },
  { name: "Suriname", code: "SR", flag: "/flags/sr.svg" },
  { name: "Svalbard and Jan Mayen", code: "SJ", flag: "/flags/sj.svg" },
  { name: "Swaziland", code: "SZ", flag: "/flags/sz.svg" },
  { name: "Sweden", code: "SE", flag: "/flags/se.svg" },
  { name: "Switzerland", code: "CH", flag: "/flags/ch.svg" },
  { name: "Syrian Arab Republic", code: "SY", flag: "/flags/sy.svg" },
  { name: "Taiwan, Province of China", code: "TW", flag: "/flags/tw.svg" },
  { name: "Tajikistan", code: "TJ", flag: "/flags/tj.svg" },
  { name: "Tanzania, United Republic of", code: "TZ", flag: "/flags/tz.svg" },
  { name: "Thailand", code: "TH", flag: "/flags/th.svg" },
  { name: "Timor-Leste", code: "TL", flag: "/flags/tl.svg" },
  { name: "Togo", code: "TG", flag: "/flags/tg.svg" },
  { name: "Tokelau", code: "TK", flag: "/flags/tk.svg" },
  { name: "Tonga", code: "TO", flag: "/flags/to.svg" },
  { name: "Trinidad and Tobago", code: "TT", flag: "/flags/tt.svg" },
  { name: "Tunisia", code: "TN", flag: "/flags/tn.svg" },
  { name: "Turkey", code: "TR", flag: "/flags/tr.svg" },
  { name: "Turkmenistan", code: "TM", flag: "/flags/tm.svg" },
  { name: "Turks and Caicos Islands", code: "TC", flag: "/flags/tc.svg" },
  { name: "Tuvalu", code: "TV", flag: "/flags/tv.svg" },
  { name: "Uganda", code: "UG", flag: "/flags/ug.svg" },
  { name: "Ukraine", code: "UA", flag: "/flags/ua.svg" },
  { name: "United Arab Emirates", code: "AE", flag: "/flags/ae.svg" },
  { name: "United Kingdom", code: "GB", flag: "/flags/gb.svg" },
  { name: "United States", code: "US", flag: "/flags/us.svg" },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    flag: "/flags/um.svg",
  },
  { name: "Uruguay", code: "UY", flag: "/flags/uy.svg" },
  { name: "Uzbekistan", code: "UZ", flag: "/flags/uz.svg" },
  { name: "Vanuatu", code: "VU", flag: "/flags/vu.svg" },
  { name: "Venezuela", code: "VE", flag: "/flags/ve.svg" },
  { name: "Viet Nam", code: "VN", flag: "/flags/vn.svg" },
  { name: "Virgin Islands, British", code: "VG", flag: "/flags/vg.svg" },
  { name: "Virgin Islands, U.S.", code: "VI", flag: "/flags/vi.svg" },
  { name: "Wallis and Futuna", code: "WF", flag: "/flags/wf.svg" },
  { name: "Western Sahara", code: "EH", flag: "/flags/eh.svg" },
  { name: "Yemen", code: "YE", flag: "/flags/ye.svg" },
  { name: "Zambia", code: "ZM", flag: "/flags/zm.svg" },
  { name: "Zimbabwe", code: "ZW", flag: "/flags/zw.svg" },
];
